Python Analysis and Feature Engineering
=======


This lab will introduce to practical code for two concepts

1. SQL style querying in Pandas 
1. SQL style data shaping in Pandas

**Notebook Setup**

In [1]:
#to allow plots to render
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
import pandas as pd
from scipy import stats

**Data Setup**

In [2]:
df = pd.read_csv('labtrain1.csv')
df.describe()

,Row_ID,Calendar_Year,Model_Year,NVVar1,NVVar2,NVVar3,NVVar4,HasLoss
count,5.332000e+03,5332.000000,5332.000000,5332.000000,5332.000000,5332.000000,5332.000000,5332.000000
mean,6.487360e+06,2006.052701,1999.383346,0.044210,0.078245,0.079615,0.055697,0.502251
std,3.825032e+06,0.815829,4.932872,1.098786,1.131062,1.128958,1.103533,0.500042
min,1.573000e+03,2005.000000,1981.000000,-0.231530,-0.266117,-0.272337,-0.251419,0.000000
25%,3.229406e+06,2005.000000,1996.000000,-0.231530,-0.266117,-0.272337,-0.251419,0.000000
50%,6.380048e+06,2006.000000,2000.000000,-0.231530,-0.266117,-0.272337,-0.251419,1.000000
75%,9.802822e+06,2007.000000,2003.000000,-0.231530,-0.266117,-0.272337,-0.251419,1.000000
max,1.318136e+07,2007.000000,2008.000000,6.627110,8.883081,8.691144,6.388802,1.000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5332 entries, 0 to 5331
Data columns (total 8 columns):
Row_ID           5332 non-null int64
Calendar_Year    5332 non-null int64
Model_Year       5332 non-null int64
NVVar1           5332 non-null float64
NVVar2           5332 non-null float64
NVVar3           5332 non-null float64
NVVar4           5332 non-null float64
HasLoss          5332 non-null int64
dtypes: float64(4), int64(4)
memory usage: 333.3 KB

SQL style querying in Pandas
----
1. SELECT or Horizontal filters
1. WHERE or Vertical filters
1. ORDER BY or Sort
1. TOP NN/ LIMIT NN
1. GROUP BY and aggregate samples
1. HAVING or filtered aggregation

**SELECT**

In [4]:
#SELECT Calendar_Year,NVVar1 from df
#by label
select_df1 = df[
    [
        "Calendar_Year"
     ,"NVVar1"
    ]
]
select_df1

      Calendar_Year    NVVar1
0              2006 -0.231530
1              2005 -0.231530
2              2006 -0.231530
3              2005 -0.231530
4              2007 -0.231530
5              2007  3.197790
6              2007 -0.231530
7              2007 -0.231530
8              2006 -0.231530
9              2006 -0.231530
10             2006 -0.231530
11             2005 -0.231530
12             2007 -0.231530
13             2007 -0.231530
14             2005 -0.231530
15             2007 -0.231530
16             2005 -0.231530
17             2007 -0.231530
18             2005 -0.231530
19             2005  2.054683
20             2007 -0.231530
21             2007 -0.231530
22             2005 -0.231530
23             2006 -0.231530
24             2007 -0.231530
25             2005 -0.231530
26             2005 -0.231530
27             2007 -0.231530
28             2006 -0.231530
29             2005 -0.231530
...             ...       ...
5302           2006 -0.231530
5303           2007 -0.231530
5304           2005 -0.231530
5305           2006 -0.231530
5306           2006 -0.231530
5307           2005 -0.231530
5308           2005  3.197790
5309           2006 -0.231530
5310           2005 -0.231530
5311           2006 -0.231530
5312           2007 -0.231530
5313           2006 -0.231530
5314           2007 -0.231530
5315           2007  2.511926
5316           2005 -0.231530
5317           2007 -0.231530
5318           2007 -0.231530
5319           2006 -0.231530
5320           2007 -0.231530
5321           2007 -0.231530
5322           2006 -0.231530
5323           2005 -0.231530
5324           2006 -0.231530
5325           2007 -0.231530
5326           2006 -0.231530
5327           2007 -0.231530
5328           2007 -0.231530
5329           2007 -0.231530
5330           2005 -0.231530
5331           2007 -0.231530

[5332 rows x 2 columns]

In [7]:
#SELECT Calendar_Year,NVVar1 from df
# by position
select_df2 = df.iloc[:, [3,1]]
select_df2

        NVVar1  Calendar_Year
0    -0.231530           2006
1    -0.231530           2005
2    -0.231530           2006
3    -0.231530           2005
4    -0.231530           2007
5     3.197790           2007
6    -0.231530           2007
7    -0.231530           2007
8    -0.231530           2006
9    -0.231530           2006
10   -0.231530           2006
11   -0.231530           2005
12   -0.231530           2007
13   -0.231530           2007
14   -0.231530           2005
15   -0.231530           2007
16   -0.231530           2005
17   -0.231530           2007
18   -0.231530           2005
19    2.054683           2005
20   -0.231530           2007
21   -0.231530           2007
22   -0.231530           2005
23   -0.231530           2006
24   -0.231530           2007
25   -0.231530           2005
26   -0.231530           2005
27   -0.231530           2007
28   -0.231530           2006
29   -0.231530           2005
...        ...            ...
5302 -0.231530           2006
5303 -0.231530           2007
5304 -0.231530           2005
5305 -0.231530           2006
5306 -0.231530           2006
5307 -0.231530           2005
5308  3.197790           2005
5309 -0.231530           2006
5310 -0.231530           2005
5311 -0.231530           2006
5312 -0.231530           2007
5313 -0.231530           2006
5314 -0.231530           2007
5315  2.511926           2007
5316 -0.231530           2005
5317 -0.231530           2007
5318 -0.231530           2007
5319 -0.231530           2006
5320 -0.231530           2007
5321 -0.231530           2007
5322 -0.231530           2006
5323 -0.231530           2005
5324 -0.231530           2006
5325 -0.231530           2007
5326 -0.231530           2006
5327 -0.231530           2007
5328 -0.231530           2007
5329 -0.231530           2007
5330 -0.231530           2005
5331 -0.231530           2007

[5332 rows x 2 columns]

In [8]:
#SELECT COUNT(*) FROM select_df2
len(select_df2)

5332

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5332 entries, 0 to 5331
Data columns (total 8 columns):
Row_ID           5332 non-null int64
Calendar_Year    5332 non-null int64
Model_Year       5332 non-null int64
NVVar1           5332 non-null float64
NVVar2           5332 non-null float64
NVVar3           5332 non-null float64
NVVar4           5332 non-null float64
HasLoss          5332 non-null int64
dtypes: float64(4), int64(4)
memory usage: 333.3 KB

In [40]:
#select only numerics
#numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
#df_numeric = df[['Calendar_Year','Model_Year']]
df_numeric = df.select_dtypes(include=numerics) 
df_numeric.describe()

,Row_ID,Calendar_Year,Model_Year,NVVar1,NVVar2,NVVar3,NVVar4,HasLoss
count,5.332000e+03,5332.000000,5332.000000,5332.000000,5332.000000,5332.000000,5332.000000,5332.000000
mean,6.487360e+06,2006.052701,1999.383346,0.044210,0.078245,0.079615,0.055697,0.502251
std,3.825032e+06,0.815829,4.932872,1.098786,1.131062,1.128958,1.103533,0.500042
min,1.573000e+03,2005.000000,1981.000000,-0.231530,-0.266117,-0.272337,-0.251419,0.000000
25%,3.229406e+06,2005.000000,1996.000000,-0.231530,-0.266117,-0.272337,-0.251419,0.000000
50%,6.380048e+06,2006.000000,2000.000000,-0.231530,-0.266117,-0.272337,-0.251419,1.000000
75%,9.802822e+06,2007.000000,2003.000000,-0.231530,-0.266117,-0.272337,-0.251419,1.000000
max,1.318136e+07,2007.000000,2008.000000,6.627110,8.883081,8.691144,6.388802,1.000000

**ORDER BY**

In [19]:
#SELECT 
#     Calendar_Year,NVVar1 
#FROM
#     df 
#ORDER BY Calendar_Year ASC
select_df1.sort_values('Calendar_Year')

      Calendar_Year   NVVar1
3958           2005 -0.23153
1525           2005 -0.23153
3670           2005 -0.23153
1523           2005 -0.23153
3671           2005 -0.23153
1520           2005  3.19779
3674           2005 -0.23153
1518           2005 -0.23153
1516           2005 -0.23153
3677           2005 -0.23153
1512           2005 -0.23153
3683           2005  1.48313
1510           2005 -0.23153
3684           2005 -0.23153
3688           2005 -0.23153
3692           2005 -0.23153
3693           2005  6.62711
1501           2005 -0.23153
3694           2005 -0.23153
3696           2005 -0.23153
3700           2005 -0.23153
1495           2005 -0.23153
3703           2005 -0.23153
1492           2005  6.62711
1491           2005  3.19779
1490           2005 -0.23153
1487           2005 -0.23153
3708           2005 -0.23153
1526           2005 -0.23153
1485           2005 -0.23153
...             ...      ...
3655           2007 -0.23153
3656           2007 -0.23153
1545           2007 -0.23153
3658           2007 -0.23153
1535           2007 -0.23153
3662           2007 -0.23153
1534           2007 -0.23153
3664           2007 -0.23153
1533           2007 -0.23153
3666           2007 -0.23153
3659           2007 -0.23153
1522           2007 -0.23153
1548           2007 -0.23153
3642           2007 -0.23153
1572           2007 -0.23153
3626           2007 -0.23153
1567           2007 -0.23153
1563           2007 -0.23153
1562           2007 -0.23153
3633           2007 -0.23153
3643           2007 -0.23153
1555           2007 -0.23153
3636           2007 -0.23153
1554           2007 -0.23153
1553           2007 -0.23153
1552           2007  1.48313
3640           2007  6.62711
1551           2007 -0.23153
3635           2007 -0.23153
5331           2007 -0.23153

[5332 rows x 2 columns]

In [21]:
#SELECT 
#     Calendar_Year,NVVar1 
#FROM
#     df 
#ORDER BY Calendar_Year DESC
select_df1.sort_values('Calendar_Year',ascending=False)

      Calendar_Year    NVVar1
5331           2007 -0.231530
3747           2007 -0.231530
1677           2007 -0.231530
1678           2007 -0.231530
1679           2007 -0.231530
1680           2007 -0.231530
3753           2007 -0.231530
3751           2007  2.054683
3745           2007 -0.231530
3758           2007  2.054683
3744           2007 -0.231530
1688           2007 -0.231530
3741           2007 -0.231530
1690           2007 -0.231530
3740           2007 -0.231530
3739           2007 -0.231530
3757           2007 -0.231530
1674           2007 -0.231530
3779           2007 -0.231530
1661           2007 -0.231530
3777           2007 -0.231530
1655           2007 -0.231530
1656           2007 -0.231530
3775           2007 -0.231530
3774           2007 -0.231530
1660           2007 -0.231530
3770           2007 -0.231530
1673           2007 -0.231530
1664           2007 -0.231530
3767           2007 -0.231530
...             ...       ...
1577           2005 -0.231530
3798           2005 -0.231530
3840           2005 -0.231530
1581           2005  6.627110
1583           2005 -0.231530
3835           2005 -0.231530
1588           2005 -0.231530
3831           2005 -0.231530
3829           2005 -0.231530
1594           2005 -0.231530
1599           2005 -0.231530
1600           2005 -0.231530
1601           2005 -0.231530
3822           2005 -0.231530
3821           2005 -0.231530
3820           2005 -0.231530
3819           2005 -0.231530
3818           2005 -0.231530
3817           2005 -0.231530
3815           2005 -0.231530
3812           2005 -0.231530
1608           2005 -0.231530
1609           2005 -0.231530
3808           2005 -0.231530
3807           2005 -0.231530
3804           2005  2.054683
1613           2005 -0.231530
3800           2005 -0.231530
3799           2005 -0.231530
2666           2005 -0.231530

[5332 rows x 2 columns]

**TOP / LIMIT**

In [28]:
#SELECT 
#Calendar_Year,NVVar1 
#FROM
#     df 
#ORDER BY Calendar_Year DESC
#LIMIT 50
select_df1.sort_values('Calendar_Year',ascending=False)[0:5]

      Calendar_Year   NVVar1
5331           2007 -0.23153
3747           2007 -0.23153
1677           2007 -0.23153
1678           2007 -0.23153
1679           2007 -0.23153

In [30]:
#SELECT 
#TOP 50 PERCENT
#Calendar_Year,NVVar1 
#FROM
#     df 
#ORDER BY Calendar_Year DESC
print("before:",len(select_df1))
#select_df1_after = select_df1.sort_values('Calendar_Year',ascending=False).head(int(df.shape[0]*.5))
select_df1_after = \
    select_df1.sort_values(
        'Calendar_Year'
        ,ascending=False
    ).head(
        int(len(select_df1)*.5)
    )
print("after:",len(select_df1_after))

before: 5332
after: 2666

In [ ]:
#         SELECT 
#              *
#         from 
#             df
#         ORDER By Calendar_Year
#         LIMIT 50

#SELECT 
#Calendar_Year,NVVar1 
#FROM
#     df 
#ORDER BY Calendar_Year DESC
#LIMIT 50
select_df1.sort_values('Calendar_Year',ascending=False)[0:50]

In [42]:
# WITH
#     foo as
#     (
#         SELECT 
#              *
#         from 
#             df
#         ORDER By Calendar_Year
#         LIMIT 50
#     )
#     SELECT 
#         Top 50% *
#     FROM
#         foo
#df_numeric = df[['Calendar_Year','Model_Year']]
print("before:",len(select_df1))
foo =select_df1[0:50].sort_values('Calendar_Year',ascending=False)
select_df2_after = foo.tail(int(round(select_df3.shape[0]*.5,0)))
print("after:",len(select_df2_after))
print(type(select_df3.shape[0]*.5))

before: 5332
after: 24
<class 'float'>

**GROUP BY**

In [43]:
# SELECT
#     Calendar_Year
#     ,COUNT(NVVar1) AS 'Calendar_Year_Count'
#     ,COUNT(DISTINCT NVVar1) AS 'Calendar_Year_Count_Distinct'
#     ,AVG(NVVar1) AS 'Calendar_Year_Count'
#     ,STDEVP(NVVar1) AS 'Calendar_Year_Count'
#     ,MIN(NVVar1) AS 'Calendar_Year_Count'
#     ,MAX(NVVar1) AS 'Calendar_Year_Count'
# FROM
#     df
# GROUP BY Calendar_Year
df_grouping = df.groupby('Calendar_Year')
df_agg1 = pd.DataFrame(
    {
        'Calendar_Year_Count':
            df_grouping.count()['NVVar1']
        , 
        'Calendar_Year_NVVar1_Count_Distinct':
            df_grouping['NVVar1'].nunique()
        ,
        'Calendar_Year_NVVar1_Avg':
            df_grouping.mean()['NVVar1']
        , 
        'Calendar_Year_NVVar1_Std':
            df_grouping.std()['NVVar1']
        , 
        'Calendar_Year_NVVar1_Min':
            df_grouping.min()['NVVar1']        
        , 
        'Calendar_Year_NVVar1_Max':
           df_grouping.max()['NVVar1']                
    }
)
df_agg1

,Calendar_Year_Count,Calendar_Year_NVVar1_Count_Distinct,Calendar_Year_NVVar1_Avg,Calendar_Year_NVVar1_Std,Calendar_Year_NVVar1_Min,Calendar_Year_NVVar1_Max
Calendar_Year,,,,,,
2005,1641,8,0.050172,1.078154,-0.23153,6.62711
2006,1769,10,0.027019,1.083560,-0.23153,6.62711
2007,1922,10,0.054943,1.130088,-0.23153,6.62711

SQL style data shaping in Pandas
----
1. AS or derived column review
1. JOIN or key based
1. UNION or schema based
1. Pandas operations that don't ft in SQL Box

**AS or derived column review**

In [44]:
# WITH 
#     NVVar1_Std as
#         (
#             SELECT
#                 STDEVP(NVVar1) AS NVVar1_Std
#             FROM 
#                 df
#         )
#     NVVar1_Avg as
#         (
#             SELECT
#                 AVG(NVVar1) AS NVVar1_Avg
#             FROM 
#                 df
#         )
# SELECT
#     Calendar_Year
#     ,NVVar1
#     ,
#         (
#             NVVar1
#             -
#             NVVar1_Avg.NVVar1_Avg
#         )
#         /
#         NVVar1_Std.NVVar1_Std
#     AS NVVar1_Z_Score
# FROM
#     df
# FULL OUTER JOIN 
#     NVVar1_Std
# ON
#     1=1
# FULL OUTER JOIN 
#     NVVar1_Avg
# ON
#     1=1
df['NVVar1_ZScore'] \
    = (
            df['NVVar1']  \
            -  \
            df['NVVar1'].mean() \
        )  \
            /  \
        df['NVVar1'].std(ddof=0)

df['NVVar1_ZScore']     = (df['NVVar1'] -  df['NVVar1'].mean() )  /df['NVVar1'].std(ddof=0)
#df['NVVar1_ZScore']= stats.zscore(df['NVVar1'], axis=1, ddof=1).to_frame()
df[["Calendar_Year","NVVar1","NVVar1_ZScore"]]

      Calendar_Year    NVVar1  NVVar1_ZScore
0              2006 -0.231530      -0.250973
1              2005 -0.231530      -0.250973
2              2006 -0.231530      -0.250973
3              2005 -0.231530      -0.250973
4              2007 -0.231530      -0.250973
5              2007  3.197790       2.870326
6              2007 -0.231530      -0.250973
7              2007 -0.231530      -0.250973
8              2006 -0.231530      -0.250973
9              2006 -0.231530      -0.250973
10             2006 -0.231530      -0.250973
11             2005 -0.231530      -0.250973
12             2007 -0.231530      -0.250973
13             2007 -0.231530      -0.250973
14             2005 -0.231530      -0.250973
15             2007 -0.231530      -0.250973
16             2005 -0.231530      -0.250973
17             2007 -0.231530      -0.250973
18             2005 -0.231530      -0.250973
19             2005  2.054683       1.829893
20             2007 -0.231530      -0.250973
21             2007 -0.231530      -0.250973
22             2005 -0.231530      -0.250973
23             2006 -0.231530      -0.250973
24             2007 -0.231530      -0.250973
25             2005 -0.231530      -0.250973
26             2005 -0.231530      -0.250973
27             2007 -0.231530      -0.250973
28             2006 -0.231530      -0.250973
29             2005 -0.231530      -0.250973
...             ...       ...            ...
5302           2006 -0.231530      -0.250973
5303           2007 -0.231530      -0.250973
5304           2005 -0.231530      -0.250973
5305           2006 -0.231530      -0.250973
5306           2006 -0.231530      -0.250973
5307           2005 -0.231530      -0.250973
5308           2005  3.197790       2.870326
5309           2006 -0.231530      -0.250973
5310           2005 -0.231530      -0.250973
5311           2006 -0.231530      -0.250973
5312           2007 -0.231530      -0.250973
5313           2006 -0.231530      -0.250973
5314           2007 -0.231530      -0.250973
5315           2007  2.511926       2.246066
5316           2005 -0.231530      -0.250973
5317           2007 -0.231530      -0.250973
5318           2007 -0.231530      -0.250973
5319           2006 -0.231530      -0.250973
5320           2007 -0.231530      -0.250973
5321           2007 -0.231530      -0.250973
5322           2006 -0.231530      -0.250973
5323           2005 -0.231530      -0.250973
5324           2006 -0.231530      -0.250973
5325           2007 -0.231530      -0.250973
5326           2006 -0.231530      -0.250973
5327           2007 -0.231530      -0.250973
5328           2007 -0.231530      -0.250973
5329           2007 -0.231530      -0.250973
5330           2005 -0.231530      -0.250973
5331           2007 -0.231530      -0.250973

[5332 rows x 3 columns]

**JOIN or key based**

In [45]:
#WITH tbl_cal AS 
# (
#SELECT
# <col> as '<col>',
# sum(1) as 'count',
# mean(<col>) as 'mean',
# stdev(<col>) as 'std',
# min(<col>) as 'min',
# PERCENTILE_DISC(0.25) OVER (PARTITION BY 1 ORDER BY <col>) as '25',
# PERCENTILE_DISC(0.50) OVER (PARTITION BY 1 ORDER BY <col>) as '50',
# PERCENTILE_DISC(0.75) OVER (PARTITION BY 1 ORDER BY <col>) as '75',
# max(<col>) as 'max'
# ...
# SELECT tbl1...
# PIVOT...

newdf = pd.read_csv('labtrain2.csv')
newdf.describe()

,Unnamed: 0,Row_ID,Calendar_Year,Model_Year,NVVar1,NVVar2,NVVar3,NVVar4,HasLoss,NVVar1_ZScore,NVVar2_ZScore,NVVar3_ZScore,NVVar4_ZScore
count,5332.000000,5.332000e+03,5332.000000,5332.000000,5332.000000,5332.000000,5332.000000,5332.000000,5332.000000,5.332000e+03,5.332000e+03,5.332000e+03,5.332000e+03
mean,2665.500000,6.487360e+06,2006.052701,1999.383346,0.044210,0.078245,0.079615,0.055697,0.502251,2.584933e-15,2.277248e-15,1.499020e-15,6.714850e-16
std,1539.360148,3.825032e+06,0.815829,4.932872,1.098786,1.131062,1.128958,1.103533,0.500042,1.000094e+00,1.000094e+00,1.000094e+00,1.000094e+00
min,0.000000,1.573000e+03,2005.000000,1981.000000,-0.231530,-0.266117,-0.272337,-0.251419,0.000000,-2.509735e-01,-3.044870e-01,-3.117792e-01,-2.783284e-01
25%,1332.750000,3.229406e+06,2005.000000,1996.000000,-0.231530,-0.266117,-0.272337,-0.251419,0.000000,-2.509735e-01,-3.044870e-01,-3.117792e-01,-2.783284e-01
50%,2665.500000,6.380048e+06,2006.000000,2000.000000,-0.231530,-0.266117,-0.272337,-0.251419,1.000000,-2.509735e-01,-3.044870e-01,-3.117792e-01,-2.783284e-01
75%,3998.250000,9.802822e+06,2007.000000,2003.000000,-0.231530,-0.266117,-0.272337,-0.251419,1.000000,-2.509735e-01,-3.044870e-01,-3.117792e-01,-2.783284e-01
max,5331.000000,1.318136e+07,2007.000000,2008.000000,6.627110,8.883081,8.691144,6.388802,1.000000,5.991626e+00,7.785305e+00,7.628571e+00,5.739472e+00

In [46]:
#SELECT a.*,b.* from df a inner JOIN newdf b on a.Calendar_Year = b.NVVar1 
#SELECT a.*,b.* from df a left JOIN newdf b on a.Calendar_Year = b.NVVar1 
#SELECT a.*,b.* from df a right JOIN newdf b on a.Calendar_Year = b.NVVar1 
#SELECT a.*,b.* from df a outer JOIN newdf b on a.Calendar_Year = b.NVVar1 
innerjoin=df.join(newdf, how="inner", lsuffix ='Calendar_Year', rsuffix ='NVVar1')
leftjoin=df.join(newdf, how="left", lsuffix ='Calendar_Year', rsuffix ='NVVar1')
righjoin=df.join(newdf, how="right", lsuffix ='Calendar_Year', rsuffix ='NVVar1')
outerjoin=df.join(newdf, how="outer", lsuffix ='Calendar_Year', rsuffix ='NVVar1')
print("rows df: ",len(df))
print("rows newdf: ",len(newdf))
print("rows innerjoin: ",len(innerjoin))
print("rows leftjoin: ",len(leftjoin))
print("rows rightjoin: ",len(righjoin))
print("rows outerjoin: ",len(outerjoin))

rows df:  5332
rows newdf:  5332
rows innerjoin:  5332
rows leftjoin:  5332
rows rightjoin:  5332
rows outerjoin:  5332

**UNION or schema based**

In [47]:
#SELECT *,NULL AS Unnamed: 0,	NULL AS NVVar2_ZScore, NULL AS	NVVar3_ZScore	NVVar4_ZScore from df
#UNION ALL
#SELECT * from newdf
df_union= pd.concat([df,newdf],ignore_index=True,sort=False)
print("rows df_union: ",len(df_union))
df_union

rows df_union:  10664

,Row_ID,Calendar_Year,Model_Year,NVVar1,NVVar2,NVVar3,NVVar4,HasLoss,NVVar1_ZScore,Unnamed: 0,NVVar2_ZScore,NVVar3_ZScore,NVVar4_ZScore
0,2888916,2006,1998,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
1,5872967,2005,2004,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
2,3914547,2006,2006,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
3,6453577,2005,2003,-0.231530,-0.266117,4.209404,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
4,9329943,2007,2001,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
5,4783416,2007,2007,3.197790,-0.266117,-0.272337,3.068692,0,2.870326,NaN,NaN,NaN,NaN
6,124027,2007,2000,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
7,6245645,2007,2007,-0.231530,-0.266117,2.715490,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
8,3945544,2006,2004,-0.231530,-0.266117,2.715490,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
9,11030803,2006,1996,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
10,9719415,2006,2004,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
11,12497044,2005,2001,-0.231530,-0.266117,-0.272337,3.068692,0,-0.250973,NaN,NaN,NaN,NaN
12,5768676,2007,2005,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
13,7588475,2007,1993,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
14,11041919,2005,1999,-0.231530,-0.266117,-0.272337,6.388802,0,-0.250973,NaN,NaN,NaN,NaN
15,9862264,2007,2001,-0.231530,-0.266117,-0.272337,1.961988,0,-0.250973,NaN,NaN,NaN,NaN
16,4563653,2005,1994,-0.231530,2.021183,1.968533,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
17,8247588,2007,1996,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
18,11310745,2005,1997,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
19,9007574,2005,1995,2.054683,-0.266117,-0.272337,-0.251419,0,1.829893,NaN,NaN,NaN,NaN
20,5580689,2007,2004,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
21,4125628,2007,2005,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
22,13171236,2005,2005,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
23,2288615,2006,1997,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
24,5500933,2007,1998,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
25,3985794,2005,2005,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
26,4385045,2005,2004,-0.231530,-0.266117,4.209404,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
27,705989,2007,1991,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
28,3351155,2006,2007,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
29,4966946,2005,2004,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10634,2516536,2006,2002,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5302.0,-0.304487,-0.311779,-0.278328
10635,2903089,2007,2003,-0.231530,-0.266117,-0.272337,1.408637,1,-0.250973,5303.0,-0.304487,-0.311779,1.226122
10636,4207896,2005,2005,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5304.0,-0.304487,-0.311779,-0.278328
10637,11820205,2006,1996,-0.231530,8.883081,-0.272337,-0.251419,1,-0.250973,5305.0,7.785305,-0.311779,-0.278328
10638,11880736,2006,2002,-0.231530,-0.266117,-0.272337,6.388802,1,-0.250973,5306.0,-0.304487,-0.311779,5.739472
10639,9545678,2005,2000,-0.231530,2.783616,-0.272337,-0.251419,1,-0.250973,5307.0,2.392110,-0.311779,-0.278328
10640,10920487,2005,1992,3.197790,-0.266117,-0.272337,3.068692,1,2.870326,5308.0,-0.304487,-0.311779,2.730572
10641,12639004,2006,2000,-0.231530,2.021183,-0.272337,1.408637,1,-0.250973,5309.0,1.717961,-0.311779,1.226122
10642,9465743,2005,1998,-0.231530,-0.266117,-0.272337,6.388802,1,-0.250973,5310.0,-0.304487,-0.311779,5.739472
10643,7472493,2006,1996,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5311.0,-0.304487,-0.311779,-0.278328
10644,2202679,2007,2006,-0.231530,-0.266117,2.715490,-0.251419,1,-0.250973,5312.0,-0.304487,2.335004,-0.278328
10645,4014918,2006,2005,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5313.0,-0.304487,-0.311779,-0.278328
10646,3484255,2007,2004,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5314.0,-0.304487,-0.311779,-0.278328
10647,10777768,2007,2002,2.511926,1.563723,-0.272337,-0.251419,1,2.246066,5315.0,1.313471,-0.311779,-0.278328
10648,9772077,2005,2000,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5316.0,-0.304487,-0.311779,-0.278328
10649,6114034,2007,1992,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5317.0,-0.304487,-0.311779,-0.278328
10650,12298347,2007,2005,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5318.0,-0.304487,-0.311779,-0.278328
10651,11235707,2006,1995,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5319.0,-0.304487,-0.311779,-0.278328
10652,1866517,2007,2005,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5320.0,-0.304487,-0.311779,-0.278328
10653,5813687,2007,2003,-0.231530,-0.266117,2.715490,-0.251419,1,-0.250973,5321.0,-0.304487,2.335004,-0.278328
10654,9860423,2006,2004,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5322.0,-0.304487,-0.311779,-0.278328
10655,1115074,2005,1994,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5323.0,-0.304487,-0.311779,-0.278328
10656,306936,2006,2003,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5324.0,-0.304487,-0.311779,-0.278328
10657,8660337,2007,2003,-0.231530,-0.266117,2.715490,-0.251419,1,-0.250973,5325.0,-0.304487,2.335004,-0.278328
10658,3988194,2006,2006,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5326.0,-0.304487,-0.311779,-0.278328
10659,5562416,2007,2007,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5327.0,-0.304487,-0.311779,-0.278328
10660,2863083,2007,2003,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5328.0,-0.304487,-0.311779,-0.278328
10661,4014919,2007,2005,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5329.0,-0.304487,-0.311779,-0.278328
10662,5030537,2005,1998,-0.231530,-0.266117,2.715490,-0.251419,1,-0.250973,5330.0,-0.304487,2.335004,-0.278328
10663,597996,2007,2003,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,5331.0,-0.304487,-0.311779,-0.278328

**Pandas operations that don't fit in SQL Box**

In [49]:
#Where SQL ends and Python begins :)
df.info()
df.groupby(
    ['Calendar_Year','Model_Year']
).agg(
    [
        'min'
        ,'max'
        ,'count'
        ,'nunique'
    ]
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5332 entries, 0 to 5331
Data columns (total 9 columns):
Row_ID           5332 non-null int64
Calendar_Year    5332 non-null int64
Model_Year       5332 non-null int64
NVVar1           5332 non-null float64
NVVar2           5332 non-null float64
NVVar3           5332 non-null float64
NVVar4           5332 non-null float64
HasLoss          5332 non-null int64
NVVar1_ZScore    5332 non-null float64
dtypes: float64(5), int64(4)
memory usage: 375.0 KB

                            Row_ID                           NVVar1            \
                               min       max count nunique      min       max
Calendar_Year Model_Year
2005          1981         2596284  12656276     4       4 -0.23153 -0.231530
              1982         2716133   9762037     2       2 -0.23153 -0.231530
              1983         3642589  10196448     4       4 -0.23153 -0.231530
              1984        12031065  12031065     1       1 -0.23153 -0.231530
              1985         5084686  13172669     5       5 -0.23153 -0.231530
              1986         4013317  12862326     6       6 -0.23153  2.054683
              1987         1130469  12286553     8       8 -0.23153 -0.231530
              1988         1811566  12626689    21      21 -0.23153  6.627110
              1989          467466  13103408    23      23 -0.23153 -0.231530
              1990          187899  12091483    19      19 -0.23153  6.627110
              1991            2906  13163173    43      43 -0.23153  6.627110
              1992          179813  12832184    45      45 -0.23153  3.197790
              1993          343199  13149956    52      52 -0.23153  4.340897
              1994          180309  13023347    75      75 -0.23153  3.197790
              1995          340838  13046924    98      98 -0.23153  3.197790
              1996          174387  13143673   100     100 -0.23153  3.197790
              1997           18308  13148387    99      99 -0.23153  6.627110
              1998          183636  13142257   105     105 -0.23153  6.627110
              1999            1573  13139086   139     139 -0.23153  6.627110
              2000          166295  13181365   136     136 -0.23153  3.197790
              2001           16488  13177187   141     141 -0.23153  6.627110
              2002          226617  13097258   139     139 -0.23153  6.627110
              2003           14113  13170179   136     136 -0.23153  6.627110
              2004            3495  13165343   138     138 -0.23153  3.197790
              2005           13784  13180123    89      89 -0.23153  6.627110
              2006         1243245  13070148    13      13 -0.23153  6.627110
2006          1981          287827  12315993     6       6 -0.23153 -0.231530
              1982         2739517   7379175     2       2 -0.23153 -0.231530
              1983         1592073   1592073     1       1 -0.23153 -0.231530
              1984          292708  12207275     2       2 -0.23153 -0.231530
...                            ...       ...   ...     ...      ...       ...
              2006          277018  13051487   109     109 -0.23153  6.627110
              2007          312659  12609056    19      19 -0.23153  2.054683
2007          1981          190515  10644897     6       6 -0.23153  6.627110
              1982         3203993   7414283     2       2 -0.23153 -0.231530
              1983         1157157  10758378     8       8 -0.23153 -0.231530
              1984         4777448   9215856     3       3 -0.23153 -0.231530
              1985           42859   9063866     7       7 -0.23153 -0.231530
              1986          412315  12187004    10      10 -0.23153 -0.231530
              1987         1275484   7585934     6       6 -0.23153  3.197790
              1988         1011964  11266143    16      16 -0.23153 -0.231530
              1989          115905  12546818    17      17 -0.23153  6.627110
              1990         1246339  12550646    18      18 -0.23153  3.197790
              1991          705989  11164578    23      23 -0.23153 -0.231530
              1992           38346  11518645    27      27 -0.23153  3.197790
              1993          251526  12324639    49      49 -0.23153  3.197790
              1994           40909  12482877    68      68 -0.23153  6.627110
              1995           86956  12457287    75      75 -0.23153  6.627110
              1996           85574  12320477    76      76 -0.23153  6.627110
              1997           43629  12513459    92      92 -0.23153  6.627110
              1998           65098  12514296   117     117 -0.23153  6.627110
              1999           60238  12522103   136     136 -0.23153  6.627110
              2000           27269  12505517   134     134 -0.23153  6.627110
              2001           22019  12516925   164     164 -0.23153  6.627110
              2002           31026  12554966   150     150 -0.23153  6.627110
              2003           95339  12441837   140     140 -0.23153  6.627110
              2004          183513  12447786   158     158 -0.23153  6.627110
              2005           38269  12486748   163     163 -0.23153  3.197790
              2006           86404  12499487   136     136 -0.23153  6.627110
              2007           66378  12496807   109     109 -0.23153  3.197790
              2008          785733  11891309    12      12 -0.23153  2.054683

                                          NVVar2            ... NVVar4  \
                         count nunique       min       max  ...  count
Calendar_Year Model_Year                                    ...
2005          1981           4       1 -0.266117 -0.266117  ...      4
              1982           2       1 -0.266117  2.783616  ...      2
              1983           4       1 -0.266117 -0.266117  ...      4
              1984           1       1 -0.266117 -0.266117  ...      1
              1985           5       1 -0.266117 -0.266117  ...      5
              1986           6       2 -0.266117 -0.266117  ...      6
              1987           8       1 -0.266117 -0.266117  ...      8
              1988          21       3 -0.266117  2.021183  ...     21
              1989          23       1 -0.266117  2.783616  ...     23
              1990          19       2 -0.266117  4.308482  ...     19
              1991          43       4 -0.266117  2.783616  ...     43
              1992          45       3 -0.266117  2.783616  ...     45
              1993          52       3 -0.266117  2.783616  ...     52
              1994          75       4 -0.266117  4.308482  ...     75
              1995          98       5 -0.266117  8.883081  ...     98
              1996         100       5 -0.266117  8.883081  ...    100
              1997          99       6 -0.266117  4.308482  ...     99
              1998         105       5 -0.266117  5.833349  ...    105
              1999         139       6 -0.266117  5.223402  ...    139
              2000         136       4 -0.266117  5.833349  ...    136
              2001         141       5 -0.266117  8.883081  ...    141
              2002         139       5 -0.266117  5.223402  ...    139
              2003         136       5 -0.266117  4.308482  ...    136
              2004         138       4 -0.266117  4.308482  ...    138
              2005          89       5 -0.266117  4.308482  ...     89
              2006          13       2 -0.266117 -0.266117  ...     13
2006          1981           6       1 -0.266117 -0.266117  ...      6
              1982           2       1 -0.266117 -0.266117  ...      2
              1983           1       1 -0.266117 -0.266117  ...      1
              1984           2       1 -0.266117 -0.266117  ...      2
...                        ...     ...       ...       ...  ...    ...
              2006         109       3 -0.266117  8.883081  ...    109
              2007          19       2 -0.266117  2.783616  ...     19
2007          1981           6       3 -0.266117 -0.266117  ...      6
              1982           2       1 -0.266117  2.783616  ...      2
              1983           8       1 -0.266117 -0.266117  ...      8
              1984           3       1 -0.266117 -0.266117  ...      3
              1985           7       1 -0.266117 -0.266117  ...      7
              1986          10       1 -0.266117 -0.266117  ...     10
              1987           6       2 -0.266117  4.308482  ...      6
              1988          16       1 -0.266117  2.021183  ...     16
              1989          17       3 -0.266117  2.783616  ...     17
              1990          18       2 -0.266117  2.783616  ...     18
              1991          23       1 -0.266117 -0.266117  ...     23
              1992          27       3 -0.266117  5.223402  ...     27
              1993          49       3 -0.266117  2.783616  ...     49
              1994          68       3 -0.266117  4.308482  ...     68
              1995          75       6 -0.266117  8.883081  ...     75
              1996          76       4 -0.266117  8.883081  ...     76
              1997          92       5 -0.266117  4.308482  ...     92
              1998         117       5 -0.266117  4.308482  ...    117
              1999         136       6 -0.266117  8.883081  ...    136
              2000         134       6 -0.266117  8.883081  ...    134
              2001         164       6 -0.266117  5.223402  ...    164
              2002         150       6 -0.266117  8.883081  ...    150
              2003         140       5 -0.266117  8.883081  ...    140
              2004         158       6 -0.266117  5.833349  ...    158
              2005         163       4 -0.266117  4.308482  ...    163
              2006         136       5 -0.266117  4.308482  ...    136
              2007         109       3 -0.266117  4.308482  ...    109
              2008          12       2 -0.266117  1.563723  ...     12

                                 HasLoss                   NVVar1_ZScore  \
                         nunique     min max count nunique           min
Calendar_Year Model_Year
2005          1981             1       0   0     4       1     -0.250973
              1982             1       0   1     2       2     -0.250973
              1983             2       0   1     4       2     -0.250973
              1984             1       0   0     1       1     -0.250973
              1985             1       0   1     5       2     -0.250973
              1986             1       0   1     6       2     -0.250973
              1987             1       0   1     8       2     -0.250973
              1988             2       0   1    21       2     -0.250973
              1989             1       0   1    23       2     -0.250973
              1990             2       0   1    19       2     -0.250973
              1991             3       0   1    43       2     -0.250973
              1992             3       0   1    45       2     -0.250973
              1993             3       0   1    52       2     -0.250973
              1994             5       0   1    75       2     -0.250973
              1995             6       0   1    98       2     -0.250973
              1996             6       0   1   100       2     -0.250973
              1997             6       0   1    99       2     -0.250973
              1998             5       0   1   105       2     -0.250973
              1999             6       0   1   139       2     -0.250973
              2000             5       0   1   136       2     -0.250973
              2001             6       0   1   141       2     -0.250973
              2002             8       0   1   139       2     -0.250973
              2003             5       0   1   136       2     -0.250973
              2004             6       0   1   138       2     -0.250973
              2005             6       0   1    89       2     -0.250973
              2006             2       0   1    13       2     -0.250973
2006          1981             1       0   1     6       2     -0.250973
              1982             1       0   0     2       1     -0.250973
              1983             1       0   0     1       1     -0.250973
              1984             1       1   1     2       1     -0.250973
...                          ...     ...  ..   ...     ...           ...
              2006             4       0   1   109       2     -0.250973
              2007             3       0   1    19       2     -0.250973
2007          1981             1       0   0     6       1     -0.250973
              1982             1       0   1     2       2     -0.250973
              1983             1       0   1     8       2     -0.250973
              1984             1       0   0     3       1     -0.250973
              1985             1       0   1     7       2     -0.250973
              1986             2       0   1    10       2     -0.250973
              1987             1       0   1     6       2     -0.250973
              1988             2       0   1    16       2     -0.250973
              1989             3       0   1    17       2     -0.250973
              1990             2       0   1    18       2     -0.250973
              1991             2       0   1    23       2     -0.250973
              1992             3       0   1    27       2     -0.250973
              1993             4       0   1    49       2     -0.250973
              1994             3       0   1    68       2     -0.250973
              1995             3       0   1    75       2     -0.250973
              1996             4       0   1    76       2     -0.250973
              1997             5       0   1    92       2     -0.250973
              1998             6       0   1   117       2     -0.250973
              1999             5       0   1   136       2     -0.250973
              2000             5       0   1   134       2     -0.250973
              2001             5       0   1   164       2     -0.250973
              2002             5       0   1   150       2     -0.250973
              2003             4       0   1   140       2     -0.250973
              2004             5       0   1   158       2     -0.250973
              2005             6       0   1   163       2     -0.250973
              2006             5       0   1   136       2     -0.250973
              2007             4       0   1   109       2     -0.250973
              2008             2       0   1    12       2     -0.250973


                               max count nunique
Calendar_Year Model_Year
2005          1981       -0.250973     4       1
              1982       -0.250973     2       1
              1983       -0.250973     4       1
              1984       -0.250973     1       1
              1985       -0.250973     5       1
              1986        1.829893     6       2
              1987       -0.250973     8       1
              1988        5.991626    21       3
              1989       -0.250973    23       1
              1990        5.991626    19       2
              1991        5.991626    43       4
              1992        2.870326    45       3
              1993        3.910760    52       3
              1994        2.870326    75       4
              1995        2.870326    98       5
              1996        2.870326   100       5
              1997        5.991626    99       6
              1998        5.991626   105       5
              1999        5.991626   139       6
              2000        2.870326   136       4
              2001        5.991626   141       5
              2002        5.991626   139       5
              2003        5.991626   136       5
              2004        2.870326   138       4
              2005        5.991626    89       5
              2006        5.991626    13       2
2006          1981       -0.250973     6       1
              1982       -0.250973     2       1
              1983       -0.250973     1       1
              1984       -0.250973     2       1
...                            ...   ...     ...
              2006        5.991626   109       3
              2007        1.829893    19       2
2007          1981        5.991626     6       3
              1982       -0.250973     2       1
              1983       -0.250973     8       1
              1984       -0.250973     3       1
              1985       -0.250973     7       1
              1986       -0.250973    10       1
              1987        2.870326     6       2
              1988       -0.250973    16       1
              1989        5.991626    17       3
              1990        2.870326    18       2
              1991       -0.250973    23       1
              1992        2.870326    27       3
              1993        2.870326    49       3
              1994        5.991626    68       3
              1995        5.991626    75       6
              1996        5.991626    76       4
              1997        5.991626    92       5
              1998        5.991626   117       5
              1999        5.991626   136       6
              2000        5.991626   134       6
              2001        5.991626   164       6
              2002        5.991626   150       6
              2003        5.991626   140       5
              2004        5.991626   158       6
              2005        2.870326   163       4
              2006        5.991626   136       5
              2007        2.870326   109       3
              2008        1.829893    12       2

[81 rows x 28 columns]

In [71]:
#hot encoding or case statements forever
df['Calendar_Year_Enum'] = df['Calendar_Year'].astype(str)
pd.get_dummies(df)

,Row_ID,Calendar_Year,Model_Year,NVVar1,NVVar2,NVVar3,NVVar4,HasLoss,NVVar1_ZScore,Calendar_Year_Enum_2005,Calendar_Year_Enum_2006,Calendar_Year_Enum_2007
0,2888916,2006,1998,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,1,0
1,5872967,2005,2004,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,1,0,0
2,3914547,2006,2006,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,1,0
3,6453577,2005,2003,-0.231530,-0.266117,4.209404,-0.251419,0,-0.250973,1,0,0
4,9329943,2007,2001,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,0,1
5,4783416,2007,2007,3.197790,-0.266117,-0.272337,3.068692,0,2.870326,0,0,1
6,124027,2007,2000,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,0,1
7,6245645,2007,2007,-0.231530,-0.266117,2.715490,-0.251419,0,-0.250973,0,0,1
8,3945544,2006,2004,-0.231530,-0.266117,2.715490,-0.251419,0,-0.250973,0,1,0
9,11030803,2006,1996,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,1,0
10,9719415,2006,2004,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,1,0
11,12497044,2005,2001,-0.231530,-0.266117,-0.272337,3.068692,0,-0.250973,1,0,0
12,5768676,2007,2005,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,0,1
13,7588475,2007,1993,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,0,1
14,11041919,2005,1999,-0.231530,-0.266117,-0.272337,6.388802,0,-0.250973,1,0,0
15,9862264,2007,2001,-0.231530,-0.266117,-0.272337,1.961988,0,-0.250973,0,0,1
16,4563653,2005,1994,-0.231530,2.021183,1.968533,-0.251419,0,-0.250973,1,0,0
17,8247588,2007,1996,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,0,1
18,11310745,2005,1997,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,1,0,0
19,9007574,2005,1995,2.054683,-0.266117,-0.272337,-0.251419,0,1.829893,1,0,0
20,5580689,2007,2004,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,0,1
21,4125628,2007,2005,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,0,1
22,13171236,2005,2005,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,1,0,0
23,2288615,2006,1997,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,1,0
24,5500933,2007,1998,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,0,1
25,3985794,2005,2005,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,1,0,0
26,4385045,2005,2004,-0.231530,-0.266117,4.209404,-0.251419,0,-0.250973,1,0,0
27,705989,2007,1991,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,0,1
28,3351155,2006,2007,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,0,1,0
29,4966946,2005,2004,-0.231530,-0.266117,-0.272337,-0.251419,0,-0.250973,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
5302,2516536,2006,2002,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,1,0
5303,2903089,2007,2003,-0.231530,-0.266117,-0.272337,1.408637,1,-0.250973,0,0,1
5304,4207896,2005,2005,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,1,0,0
5305,11820205,2006,1996,-0.231530,8.883081,-0.272337,-0.251419,1,-0.250973,0,1,0
5306,11880736,2006,2002,-0.231530,-0.266117,-0.272337,6.388802,1,-0.250973,0,1,0
5307,9545678,2005,2000,-0.231530,2.783616,-0.272337,-0.251419,1,-0.250973,1,0,0
5308,10920487,2005,1992,3.197790,-0.266117,-0.272337,3.068692,1,2.870326,1,0,0
5309,12639004,2006,2000,-0.231530,2.021183,-0.272337,1.408637,1,-0.250973,0,1,0
5310,9465743,2005,1998,-0.231530,-0.266117,-0.272337,6.388802,1,-0.250973,1,0,0
5311,7472493,2006,1996,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,1,0
5312,2202679,2007,2006,-0.231530,-0.266117,2.715490,-0.251419,1,-0.250973,0,0,1
5313,4014918,2006,2005,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,1,0
5314,3484255,2007,2004,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,0,1
5315,10777768,2007,2002,2.511926,1.563723,-0.272337,-0.251419,1,2.246066,0,0,1
5316,9772077,2005,2000,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,1,0,0
5317,6114034,2007,1992,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,0,1
5318,12298347,2007,2005,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,0,1
5319,11235707,2006,1995,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,1,0
5320,1866517,2007,2005,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,0,1
5321,5813687,2007,2003,-0.231530,-0.266117,2.715490,-0.251419,1,-0.250973,0,0,1
5322,9860423,2006,2004,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,1,0
5323,1115074,2005,1994,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,1,0,0
5324,306936,2006,2003,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,1,0
5325,8660337,2007,2003,-0.231530,-0.266117,2.715490,-0.251419,1,-0.250973,0,0,1
5326,3988194,2006,2006,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,1,0
5327,5562416,2007,2007,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,0,1
5328,2863083,2007,2003,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,0,1
5329,4014919,2007,2005,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,0,1
5330,5030537,2005,1998,-0.231530,-0.266117,2.715490,-0.251419,1,-0.250973,1,0,0
5331,597996,2007,2003,-0.231530,-0.266117,-0.272337,-0.251419,1,-0.250973,0,0,1